minor_changes:
  - "Add a ``antsibull-nox`` CLI tool with a subcommand ``lint-config`` that lints the config file (https://github.com/ansible-community/antsibull-nox/pull/56)."
  - "Add a session for linting the antsibull-nox configuration to ``lint`` (https://github.com/ansible-community/antsibull-nox/pull/56)."
